@startuml
hide circle
skinparam classAttributeIconSize 0

title Klassen

class historicWeather {
    +temperature2M: Double
    +freezingLevelHeight: Double
    +relativeHumidity2M: Int
    +rain: Double
    -time: Date
    setHistoricWeather()
    getDataAt()
}

class currentWeather {
    +temperature2M: Double
    +freezingLevelHeight: Double
    +relativeHumidity2M: Int
    +rain: Double
    -time: Date
    getCurrentWeather()
    saveCurrentWeather()

}


@enduml